services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn fastapi_app.main:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: streamlit-frontend
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app/app.py --server.port 10001 --server.address 0.0.0.0"
    autoDeploy: true
